### ISSUE TITLE
Stats for the README

### ISSUE THREAD

**Issue by wegry** [texastoland/purescript-tree-shaking-test#1]
Would you mind if in this repo I ran webpack and rollup and committed the respective bundles? Or maybe just stats for bundle/minified/and gzipped and the equivalent for psc-bundle for the README for transparency's sake?

**Comment by texastoland** [comment]
Sounds good! Let's wait for real output. The current iteration is somewhat contrived because I did the minimal modification necessary.

**Comment by wegry** [comment]
Thanks for the heads up. 😉 I'll probably create a clone of your src directory for profiling release output in the meantime.
